ATHD-5078 updated http data receiver
icanbwell/SparkPipelineFramework pull request #240
Opened 2023-04-26 12:41 UTC by RunjeethNikam

2023-04-27 12:16 UTC, gagan-chawla requested changes

2023-04-27 12:16 UTC, gagan-chawla commented on spark_pipeline_framework/transformers/http_data_receiver/v4/http_data_receiver.py
> +        return desired_partitions or 1
move above

2023-04-27 12:16 UTC, gagan-chawla commented on spark_pipeline_framework/transformers/framework_run_function_transformer/v2/run_function_transformer.py
> +        return self.getOrDefault(self.fn)
fix type``

2023-04-27 12:16 UTC, gagan-chawla commented on spark_pipeline_framework/transformers/http_data_receiver/v4/http_data_receiver_processor.py
>                  )
make it concise

2023-04-27 16:22 UTC, RunjeethNikam commented on spark_pipeline_framework/transformers/http_data_receiver/v4/http_data_receiver_processor.py
>                  )
Done

2023-04-28 10:02 UTC, gagan-chawla requested changes

2023-04-28 10:02 UTC, gagan-chawla commented on spark_pipeline_framework/transformers/framework_run_function_transformer/v2/run_function_transformer.py
> +        fn_kwargments: Optional[Dict[str, Any]] = None
use fn_args and fn_kwargs

2023-04-28 10:02 UTC, gagan-chawla commented on spark_pipeline_framework/transformers/http_data_receiver/v4/http_data_receiver_processor.py
> +            assert isinstance(data, list)
instead of asserting. can you not redefine the type?

2023-04-28 11:01 UTC, gagan-chawla approved these changes

2023-04-28 11:27 UTC, merged